name: Weekly Release

on:
  schedule:
    - cron: '0 0 * * 1' # 매주 월요일 자정에 실행
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run Node.js script and save output
      run: node index.js

    - name: Set output
      run: echo "output=$(cat result.txt)" >> $GITHUB_ENV

    - name: Check output
      run: |
        if [[ -z "${{ env.output }}" ]]; then
          echo "The output is empty."
        else
          echo "The output is not empty."
        fi

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.DH_LOTTERY_TOKEN }}
      with:
        tag_name: ${{ github.run_id }}
        release_name: Release ${{ github.run_number }}
        body: ${{ steps.read_output.outputs.result }}
        draft: false
        prerelease: false
